[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm ci --legacy-peer-deps']

[phases.build]
cmds = ['NODE_OPTIONS="--max-old-space-size=8192" npm run build']

[start]
cmd = 'npm start'
